M48
; DRILL file {KiCad 7.0.1-0} date 2023 April 23, Sunday 15:52:58
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-23T15:52:58-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1-0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0945
%
G90
G05
T1
X3.75Y-3.31
X4.32Y-4.41
X4.8071Y-3.767
X5.2Y-5.18
X8.2114Y-3.76
X8.23Y-5.08
X8.93Y-4.5044
T0
M30
