M48
; DRILL file {KiCad 7.0.1-0} date 2023 April 14, Friday 08:17:51
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-14T08:17:51-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1-0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0945
%
G90
G05
T1
X3.75Y-3.31
X4.32Y-4.41
X5.2Y-5.18
X7.92Y-3.86
X8.23Y-5.08
X9.03Y-2.92
T0
M30
