M48
; DRILL file {KiCad (7.0.0-0)} date Sunday, July 23, 2023 at 12:51:36 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-07-23T12:51:36-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-0)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C1.000
%
G90
G05
T1
X90.42Y-52.0
X90.42Y-54.54
X92.96Y-52.0
X92.96Y-54.54
X95.5Y-52.0
X95.5Y-54.54
T0
M30
